-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE*AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS P 
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
      WHERE MONTH(PRODUCE_DATE) = '05' AND  YEAR(PRODUCE_DATE) = '2022' 
      GROUP BY PRODUCT_ID) AS O USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC